### ISSUE TITLE
Missing golang badge from dashboard

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#17]
![image](https://cloud.githubusercontent.com/assets/2653109/22989865/a65f0bb2-f374-11e6-9494-15e5fdc5c0fb.png)

**Comment by glinton** [comment]
nodejs icon is also missing. According to @Tolmark12 `"serviceType": null` is the cause, it should be `nodejs` and likely `golang`

**Comment by Tolmark12** [comment]
Fixed ready for deploy. See : https://github.com/nanobox-io/nanobox-dash-ui-clobber-box/commit/ae57bab786103a92c2533ebc333fa43dfda915bc

**Comment by glinton** [comment]
Would it be useful to add plain `go` as well as `nodejs` to that as well? I see it is [currently only looking for `node`](https://github.com/nanobox-io/nanobox-dash-ui-clobber-box/commit/ae57bab786103a92c2533ebc333fa43dfda915bc#diff-5c4f0de38622f12de7fc28252ded806dR52)

**Comment by glinton** [comment]
go works! but storage still doesn't
![image](https://cloud.githubusercontent.com/assets/2653109/23816204/c430266c-05a8-11e7-8563-7a74120f9502.png)

**Comment by Tolmark12** [comment]
Fixed, ready for deploy : `bower update clobberbox`

**Comment by jedgalbraith** [comment]
deployed
